language: go
sudo: false

go:
  - 1.7.1
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=sled.coverprofile .
  - go test -coverprofile=config.coverprofile ./config
  - go test -coverprofile=events.coverprofile ./events
  - go test -coverprofile=storage.coverprofile ./storage
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci

