language: go
sudo: false

go:
  - 1.7.1
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
script:
  - go test -coverprofile=asset.coverprofile ./asset
  - go test -coverprofile=db.coverprofile ./db
  - go test -coverprofile=env.coverprofile ./env
  - go test -coverprofile=env.coverprofile .net/api/v1/assets
  - go test -coverprofile=c4test.coverprofile ./test
  - go test -coverprofile=cli.coverprofile ./cmd/c4
  - go test -coverprofile=daemon.coverprofile ./cmd/c4d
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci
